import { GACCESSLEVELS } from './GACCESSLEVELS';
import { GECCLESIASTICALFIELD } from './GECCLESIASTICALFIELD';

export type GUSERPROFILES = {
  ID: string;
  NAME: string;
  GUSERS_ID: string;
  GECCLESIASTICALFIELD_ID: string;
  GECCLESIASTICALFIELD: GECCLESIASTICALFIELD;
  GACCESSLEVELS_ID: string;
  GACCESSLEVELS: GACCESSLEVELS;
  DEFAULTPROFILE: boolean;
  CREATED_AT: string;
  UPDATED_AT: string;
};
